[project]
name = "niwrap"
version = "{{VERSION}}"
description = "Neuroimaging Python wrappers"
readme = "README.md"
license = "LGPL-2.1"
authors = [{ name = "CMI DAIR", email = "dair@childmind.org" }]
requires-python = ">=3.10"
dependencies = [
  "styxdocker",
  "styxsingularity",
  "styxgraph",
{{DEPENDENCIES}}
]

[tool.hatch.build.targets.wheel]
packages = ["src/niwrap"]

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"