[project]
name = "niwrap_{{PACKAGE}}"
version = "{{VERSION}}"
description = "{{PACKAGE_DESCRIPTION}}"
license = "LGPL-2.1"
authors = [{ name = "CMI DAIR", email = "dair@childmind.org" }]
requires-python = ">=3.10"
dependencies = [
    "styxdefs{{STYXDEFS_VERSION}}"
]

[tool.hatch.build.targets.wheel]
packages = ["src/niwrap_{{PACKAGE}}"]

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"